name: 'Bazel Build Workflows'
on: [push]
jobs:
  build_code:
    name: 'Build code'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code onto runner'
        uses: actions/checkout@v2 # https://github.com/marketplace/actions/checkout

      - name: 'System Bazel version'
        run: bazel --version

      - name: 'Bazel build stage1'
        run: cd cpp-tutorial/stage1 && bazel build //main:hello-world
      - name: 'Bazel run stage1'
        run: cd cpp-tutorial/stage1 && bazel run //main:hello-world

      - name: 'Bazel build stage2'
        run: cd cpp-tutorial/stage2 && bazel build //main:hello-world

      - name: 'Bazel build stage3'
        run: cd cpp-tutorial/stage3 && bazel build //main:hello-world

      - name: 'Bazel build third-party-dependencies'
        run: cd third-party-dependencies && bazel build //:hello_world && bazel --version

      - name: 'Bazel test third-party-dependencies'
        run: cd third-party-dependencies && bazel test //:all --test_output=streamed

      - name: 'Code Coverage'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
